#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
# Firewall port 80
sudo ufw allow 'Nginx HTTP'

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

sed -i '/listen 80 default_server/a error_page 404 /404.html; location = /404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default

sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx reload
sudo service nginx start
