#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Install HAproxy version 2.0 LTS
# sudo apt-get install software-properties-common
# sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

#In order to manage HAProxy via an init script
echo "ENABLED=1" >> /etc/default/haproxy

cat >> /etc/haproxy/haproxy.cfg << EOF
frontend front
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    server 1572-web-01 34.75.244.196:80 check
    server 1572-web-02 54.85.50.33:80 check
EOF
service haproxy restart
