#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
# Your script should only display:username, user id, path for the user

dir=/etc/passwd
while read line; do
    echo "$line" | cut -f 1,3,6 -d ":"
done < "$dir"
