#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration, displays Holberton School for the other iterations
i=1
while [ $i -le 10 ]
do 

    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 9 ]
    then 
        echo "good luck"
    else
        echo "Holberton School"
    fi
    let i++
done
