#!/usr/bin/env bash
# This script is displaying "Holberton School" 20 times displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

CONTADOR=1
while [  $CONTADOR -lt 20 ]; do
    case $CONTADOR in 
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    echo "$CONTADOR"
    let CONTADOR+=1 
done
