#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01
sudo apt -y update && apt -y upgrade
sudo apt -y install ufw
ufw disable
ufw default deny incoming
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw enable
